In [2]:
from sqlalchemy import create_engine
import pandas as pd
engine = create_engine("postgresql+psycopg2://postgres:postgres@localhost:5432/postgres")

def run_query(query):
    return pd.read_sql_query(query, engine)

# Create & Insert — schema and seed data

This notebook assumes the database schema and example rows are created using the `week7/init.sql` file.
Use `CREATE TABLE` to define tables, columns, primary keys, and foreign keys. Use `INSERT` to add sample data for queries and JOIN examples.

Key points:
- Define constraints (PRIMARY KEY, UNIQUE) and foreign key references so JOINs work as expected.
- Use sensible data types (DATE, VARCHAR, DECIMAL) to allow aggregation and date functions.
- Seed enough rows to exercise window functions and aggregates (several customers, orders, payments).

Minimal example (creates a small `customers` table and inserts one row):
```sql
CREATE TABLE customers (
  customer_id SERIAL PRIMARY KEY,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  email VARCHAR(100) UNIQUE,
  signup_date DATE
);

INSERT INTO customers (first_name, last_name, email, signup_date) VALUES
('Jane','Doe','jane@example.com','2024-01-01');
```

For more queries please refer init.sql

# Updating Records

The `UPDATE` command modifies existing data in a table.  
In this example, we correct a supplier’s email address in the `suppliers` table.
```sql
UPDATE suppliers
SET contact_email = 'support@techworld.com'
WHERE supplier_name = 'TechWorld Electronics';
```

# 1. Basics

- **SELECT** – Chooses `customer_id` and `status` columns to display basic order information.  
- **FROM** – Reads data from the `orders` table.  
- **WHERE** – Filters out orders with a `Cancelled` status.  
- **GROUP BY** – Groups results by each unique combination of `customer_id` and `status`.  
- **HAVING** – Keeps only rows where the `customer_id` value is not null.  
- **ORDER BY** – Sorts results by `customer_id` in ascending order.  
- **LIMIT** – Restricts the query output to the first 10 rows.

In [10]:
query = """
SELECT customer_id, status
FROM orders
WHERE status != 'Cancelled'
GROUP BY customer_id, status
HAVING customer_id IS NOT NULL
ORDER BY customer_id ASC
LIMIT 10;
"""
run_query(query)

   customer_id     status
0            1  Completed
1            1    Pending
2            2  Completed
3            4  Completed
4            5    Pending
5            6  Completed
6            7  Completed

# 2. Aggregate

This query shows how aggregation and grouping can be done within a single table,  
without combining multiple datasets using JOINs.
- **SELECT** – Retrieves `status` and the average order value for each status.  
- **FROM** – Uses only the `orders` table.  
- **GROUP BY** – Groups all rows by order `status` (e.g., Completed, Pending, Cancelled).  
- **ORDER BY** – Sorts statuses by their average order value in descending order.

In [11]:
q = """
SELECT status, ROUND(AVG(total_amount), 2) AS avg_order_value
FROM orders
GROUP BY status
ORDER BY avg_order_value DESC;
"""
run_query(q)

      status  avg_order_value
0    Pending           524.99
1  Completed           281.65
2  Cancelled            49.99

# 3. Joins

### Inner Join

Returns rows that exist in **both** tables,  
e.g., only customers who have placed orders.

In [12]:
q = """
SELECT c.first_name, c.last_name, o.order_id, o.status, o.total_amount
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
ORDER BY c.first_name ASC;
"""
run_query(q)

   first_name last_name  order_id     status  total_amount
0         Ava     Patel        12  Completed         79.98
1      Carlos    Mendez        11  Completed        149.99
2      Carlos    Mendez        10  Completed        499.99
3        Emma    Watson         4  Completed        229.98
4        Emma    Watson         5  Completed         49.99
5        John       Doe         1  Completed       1049.98
6        John       Doe         2  Completed        124.98
7        John       Doe         3    Pending         49.99
8          Li       Wei         8  Completed        279.98
9          Li       Wei         7  Completed         69.98
10        Raj    Sharma         6  Cancelled         49.99
11     Sophia     Lopez         9    Pending        999.99

### Left Join

Returns **all rows from the left table (`customers`)**,  
  and matching rows from the right (`orders`) if they exist.  
  → Customers without any orders will still appear, with NULL values for order columns.

In [13]:
q = """
SELECT c.first_name, c.last_name, o.order_id, o.status
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
ORDER BY c.first_name ASC;
"""
run_query(q)

   first_name last_name  order_id     status
0         Ava     Patel        12  Completed
1      Carlos    Mendez        11  Completed
2      Carlos    Mendez        10  Completed
3        Emma    Watson         4  Completed
4        Emma    Watson         5  Completed
5        John       Doe         1  Completed
6        John       Doe         2  Completed
7        John       Doe         3    Pending
8          Li       Wei         8  Completed
9          Li       Wei         7  Completed
10        Raj    Sharma         6  Cancelled
11     Sophia     Lopez         9    Pending

### Right Join

Returns **all rows from the right table (`orders`)**,  
  and matching rows from `customers` when available.  
  → Useful for finding orphaned orders without matching customers.

In [14]:
q = """
SELECT c.first_name, c.last_name, o.order_id, o.status
FROM customers c
RIGHT JOIN orders o ON c.customer_id = o.customer_id
ORDER BY o.order_id ASC;
"""
run_query(q)

   first_name last_name  order_id     status
0        John       Doe         1  Completed
1        John       Doe         2  Completed
2        John       Doe         3    Pending
3        Emma    Watson         4  Completed
4        Emma    Watson         5  Completed
5         Raj    Sharma         6  Cancelled
6          Li       Wei         7  Completed
7          Li       Wei         8  Completed
8      Sophia     Lopez         9    Pending
9      Carlos    Mendez        10  Completed
10     Carlos    Mendez        11  Completed
11        Ava     Patel        12  Completed

# 4. CASE WHEN

- **SELECT** – Retrieves `order_id` and `total_amount` from the `orders` table.  
- **CASE WHEN** – Creates a new derived column `order_size` based on conditions:
  - `>= 500` → labelled as **High Value**
  - `BETWEEN 100 AND 499` → labelled as **Medium Value**
  - Otherwise → **Low Value**
  
- **ORDER BY** – Sorts results by `total_amount` in descending order,  
  so high-value orders appear first.

`CASE WHEN` is a powerful SQL feature for **data cleaning and transformation**.  
It allows you to **categorize continuous values** into **meaningful business groups**,  
such as customer tiers, price segments, or order priority levels.

In [15]:
q = """
SELECT order_id, total_amount,
       CASE 
           WHEN total_amount >= 500 THEN 'High Value'
           WHEN total_amount BETWEEN 100 AND 499 THEN 'Medium Value'
           ELSE 'Low Value'
       END AS order_size
FROM orders
ORDER BY total_amount DESC;
"""
run_query(q)

    order_id  total_amount    order_size
0          1       1049.98    High Value
1          9        999.99    High Value
2         10        499.99     Low Value
3          8        279.98  Medium Value
4          4        229.98  Medium Value
5         11        149.99  Medium Value
6          2        124.98  Medium Value
7         12         79.98     Low Value
8          7         69.98     Low Value
9          6         49.99     Low Value
10         5         49.99     Low Value
11         3         49.99     Low Value

# 5. Data Cleaning and Window Functions

- **SELECT** – Displays each customer’s name and their total spending (`SUM(o.total_amount)`).  
- **JOIN** – Combines `customers` and `orders` using `customer_id`.  
- **GROUP BY** – Aggregates total spending per customer.  
- **RANK() OVER (ORDER BY SUM(o.total_amount) DESC)** –  
  Assigns a **ranking** based on total spending, where:
  - The **highest spender** gets rank 1.  
  - Customers with the same total spending receive the same rank (ties allowed).  

- **ORDER BY total_spent DESC** – Sorts the results so top spenders appear first.

Window functions like `RANK()`, `ROW_NUMBER()`, and `DENSE_RANK()` are crucial for:
- Ranking users, sales, or transactions.  
- Identifying top-performing customers or products.  
- Performing advanced analytics **without losing row-level detail**.

Example extensions:
```sql
-- ROW_NUMBER(): assigns a unique sequential number to each row
ROW_NUMBER() OVER (ORDER BY SUM(o.total_amount) DESC)

-- PARTITION BY: ranks customers within each country
RANK() OVER (PARTITION BY c.country ORDER BY SUM(o.total_amount) DESC)
```

In [18]:
q = """
SELECT c.first_name, c.last_name,
       SUM(o.total_amount) AS total_spent,
       RANK() OVER (ORDER BY SUM(o.total_amount) DESC) AS spend_rank
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY total_spent DESC;
"""
run_query(q)

  first_name last_name  total_spent  spend_rank
0       John       Doe      1224.95           1
1     Sophia     Lopez       999.99           2
2     Carlos    Mendez       649.98           3
3         Li       Wei       349.96           4
4       Emma    Watson       279.97           5
5        Ava     Patel        79.98           6
6        Raj    Sharma        49.99           7

# 6. CTE (WITH)


This query identifies the **top 5 customers** by total spending using a **CTE** for modular and readable SQL.

### Breakdown of Logic

- **CTE 1 — `customer_sales`**  
  - Joins `customers` and `orders` to calculate each customer’s total amount spent.  
  - Filters only `Completed` orders.  
  - Aggregates results using `SUM(o.total_amount)` and groups by customer details.

- **CTE 2 — `top_customers`**  
  - Applies a **window function** `RANK()` to rank customers by their total spending in descending order.  
  - Each customer receives a rank (ties allowed for equal totals).

- **Final SELECT**  
  - Retrieves customers with `spend_rank <= 5`, showing the top 5 spenders.  
  - Orders the final output by `spend_rank`.

CTEs make complex queries more readable and reusable.  
They are ideal for:
- Breaking down **multi-step aggregations** into clear subqueries.  
- Ranking or filtering based on intermediate results.  
- Preparing data pipelines for **reporting or analytics dashboards**.

Example extension:
```sql
-- Identify top products by total quantity sold
WITH product_sales AS (
  SELECT p.product_name, SUM(oi.quantity) AS total_sold
  FROM products p
  JOIN order_items oi ON p.product_id = oi.product_id
  GROUP BY p.product_name
)
SELECT * FROM product_sales ORDER BY total_sold DESC LIMIT 5;

In [17]:
q = '''
WITH customer_sales AS (
    SELECT c.customer_id, c.first_name, c.last_name, SUM(o.total_amount) AS total_spent
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    WHERE o.status = 'Completed'
    GROUP BY c.customer_id, c.first_name, c.last_name
),
top_customers AS (
    SELECT *, RANK() OVER (ORDER BY total_spent DESC) AS spend_rank
    FROM customer_sales
)
SELECT first_name, last_name, total_spent, spend_rank
FROM top_customers
WHERE spend_rank <= 5
ORDER BY spend_rank;
'''
run_query(q)

  first_name last_name  total_spent  spend_rank
0       John       Doe      1174.96           1
1     Carlos    Mendez       649.98           2
2         Li       Wei       349.96           3
3       Emma    Watson       279.97           4
4        Ava     Patel        79.98           5

# 7. Additional Functions

### Lead Lag
- **SELECT** – Retrieves each customer’s `order_id`, `order_date`,  
  and calculates two additional insights:
  - `prev_order` → The **previous order date** for the same customer.
  - `days_between` → The **time gap** (in days) between consecutive orders.

- **LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date)** –  
  Looks at the **previous row** (prior order) **within the same customer** group,  
  determined by the `ORDER BY` sequence of order dates.

- **ORDER BY customer_id, order_date** –  
  Ensures results are displayed in chronological order per customer.

`LAG()` and `LEAD()` are essential window functions for **temporal or behavioral analysis**, such as:
- Measuring **purchase frequency** or customer re-order intervals.  
- Detecting **inactive customers** (large gaps between orders).  
- Comparing values between **current and previous events**.

Example extension:
```sql
LEAD(order_date) OVER (PARTITION BY customer_id ORDER BY order_date)
-- Finds the next order date instead of the previous one.
```

In [33]:
q = '''SELECT customer_id, order_id, order_date,
       LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_order,
       order_date - LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS days_between
FROM orders
ORDER BY customer_id, order_date;
'''
run_query(q)

    customer_id  order_id  order_date  prev_order  days_between
0             1         1  2024-07-10        None           NaN
1             1         2  2024-07-20  2024-07-10          10.0
2             1         3  2024-08-05  2024-07-20          16.0
3             2         4  2024-07-12        None           NaN
4             2         5  2024-08-01  2024-07-12          20.0
5             3         6  2024-07-15        None           NaN
6             4         7  2024-07-16        None           NaN
7             4         8  2024-07-30  2024-07-16          14.0
8             5         9  2024-07-18        None           NaN
9             6        10  2024-07-19        None           NaN
10            6        11  2024-08-02  2024-07-19          14.0
11            7        12  2024-07-22        None           NaN

### Union & Union ALL
- **SELECT** – Retrieves `order_id`, `status`, and `total_amount` from the `orders` table.  
- **WHERE** – Filters for two specific conditions:
  - The first query selects **Completed** orders.
  - The second query selects **Pending** orders.
  
- **UNION** – Combines the results of both queries into a **single result set** while automatically removing duplicates.  
  *(If duplicates should be kept, use `UNION ALL` instead.)*

- **ORDER BY order_id** – Sorts the final combined result set by `order_id`.

`UNION` and `UNION ALL` are powerful tools for:
- **Merging filtered subsets** of the same table (e.g., multiple statuses).  
- **Combining results** from different tables with identical column structures.  
- Supporting **data aggregation across partitions** or time periods.

Example:
```sql
-- Include duplicates if necessary
SELECT * FROM orders WHERE status = 'Completed'
UNION ALL
SELECT * FROM orders WHERE status = 'Pending';
Copy code

In [34]:
q = '''SELECT order_id, status, total_amount FROM orders WHERE status = 'Completed'
UNION
SELECT order_id, status, total_amount FROM orders WHERE status = 'Pending'
ORDER BY order_id;
'''
run_query(q)

    order_id     status  total_amount
0          1  Completed       1049.98
1          2  Completed        124.98
2          3    Pending         49.99
3          4  Completed        229.98
4          5  Completed         49.99
5          7  Completed         69.98
6          8  Completed        279.98
7          9    Pending        999.99
8         10  Completed        499.99
9         11  Completed        149.99
10        12  Completed         79.98

### DATE_TRUNC & COALESCE

- **DATE_TRUNC('month', o.order_date)** – Rounds each `order_date` down to the **first day of its month**,  
  enabling monthly aggregation of sales data.

- **LEFT JOIN payments p ON o.order_id = p.order_id** –  
  Includes all orders even if **no payment record exists**, ensuring months with no completed payments still appear.

- **COALESCE(SUM(p.amount), 0)** –  
  Replaces `NULL` values with `0`, so months without payments are shown as `0` total sales instead of `NULL`.

- **GROUP BY month** – Aggregates sales data by month.  
- **ORDER BY month** – Displays results chronologically.

This query demonstrates **temporal aggregation** and **data cleaning** techniques that are critical in analytics:
- `DATE_TRUNC()` helps group data by consistent time intervals (e.g., month, quarter, year).  
- `COALESCE()` ensures clean numeric results when handling missing or incomplete data.  

Example variations:
```sql
-- Aggregate by quarter instead
SELECT DATE_TRUNC('quarter', order_date), SUM(amount) FROM payments GROUP BY 1;

-- Replace missing text values
SELECT COALESCE(customer_name, 'Unknown') AS customer FROM customers;

In [35]:
q = '''SELECT DATE_TRUNC('month', o.order_date) AS month,
       COALESCE(SUM(p.amount), 0) AS total_sales
FROM orders o
LEFT JOIN payments p ON o.order_id = p.order_id
GROUP BY month
ORDER BY month;
'''
run_query(q)

                      month  total_sales
0 2024-07-01 00:00:00+00:00      2334.87
1 2024-08-01 00:00:00+00:00       199.98